### ISSUE TITLE
V1410 - SHA1 PCR bank is unusable

### ISSUE THREAD

**Issue by pkubaj** [Dasharo/dasharo-issues#819]
### Component

Dasharo firmware

### Device

other

### Dasharo version

0.9.0rc2

### Brief summary

SHA1 PCR bank on V1410 is not usable

### How to reproduce

Trying to enable SHA1 PCR bank on V1410 is not working - saving doesn't seem to save the setting.

### Expected behavior

SHA1 PCR bank should work corrently

### Actual behavior

```
root@3mdeb:~# tpm2_getcap pcrs
selected-pcrs:
  - sha1: [ ]
  - sha256: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]
```
